// File generated by direct Firebase API scripting query.
// All rights reserved. Do not modify.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Flutter apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2PYhYv5dKl2RX_ZKaWCnYmNCKkYS5hTM',
    appId: '1:373137861221:web:4a5172808feaa0d494f48c',
    messagingSenderId: '373137861221',
    projectId: 'employeecrudcollege',
    authDomain: 'employeecrudcollege.firebaseapp.com',
    storageBucket: 'employeecrudcollege.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2PYhYv5dKl2RX_ZKaWCnYmNCKkYS5hTM',
    appId: '1:373137861221:android:0ac875f6dba8cbfb94f48c',
    messagingSenderId: '373137861221',
    projectId: 'employeecrudcollege',
    storageBucket: 'employeecrudcollege.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2PYhYv5dKl2RX_ZKaWCnYmNCKkYS5hTM',
    appId: '1:373137861221:ios:2bbd3e7bcae2f78394f48c',
    messagingSenderId: '373137861221',
    projectId: 'employeecrudcollege',
    storageBucket: 'employeecrudcollege.firebasestorage.app',
    iosBundleId: 'com.luxury.jewellery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2PYhYv5dKl2RX_ZKaWCnYmNCKkYS5hTM',
    appId: '1:373137861221:ios:2bbd3e7bcae2f78394f48c',
    messagingSenderId: '373137861221',
    projectId: 'employeecrudcollege',
    storageBucket: 'employeecrudcollege.firebasestorage.app',
    iosBundleId: 'com.luxury.jewellery',
  );
}
